[theme]
primaryColor = "#636EFA"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false

[browser]
gatherUsageStats = false
